#!/usr/bin/env php
<?php

require_once('./vendor/autoload.php');

array_shift($argv);
$str = implode(', ', $argv);
if (in_array('-v', $argv, true)) {
    $output = "My version is ... already you know.";
} else {
    $output = "You said '$str'";
}

echo "\n", $output, "\n\n";

$fp = fopen('../logs/commandline/executed.log', 'ab');
$date = date('Y-m-d H:i:s');
fwrite($fp, "{$date} : {$output}\n");
fclose($fp);
